print("Enter the words in order to form a sentence")
a = input("Enter Word 1: ")
b = input("Enter Word 2: ")
c = input("Enter Word 3: ")
d = input("Enter Word 4: ")
e = input("Enter Word 5: ")
print(a,b,c,d,(e+"."))